# Generated by Django 2.0.10 on 2019-05-07 03:07

from django.db import migrations, models
import instagram_server.models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to=instagram_server.models.img_profile_location),
        ),
    ]
